version: "3.9"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: frontend-api
        env_file:
          - .env
        ports:
          - "3001:3001"
